# Generated by Django 3.1.7 on 2021-04-21 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='myimage',
            table='MyImage',
        ),
    ]
